@echo off
echo ==> Cleaning project...
call flutter clean
echo ==> Getting dependencies...
call flutter pub get
echo ==> Generating launcher icons...
call flutter pub run flutter_launcher_icons
echo ==> Building release AAB...
call flutter build appbundle --release
echo ==> Done! AAB location:
echo build\app\outputs\bundle\release\app-release.aab
pause
